INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'Martin',TIMESTAMP '2018-10-01 00:01:01','First message in guestbook!');

INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 1',TIMESTAMP '2018-10-01 01:30:00','Another message in guestbook 1.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 2',TIMESTAMP '2018-10-02 01:30:00','Another message in guestbook 2.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 3',TIMESTAMP '2018-10-03 01:30:00','Another message in guestbook 3.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 4',TIMESTAMP '2018-10-04 01:30:00','Another message in guestbook 4.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 5',TIMESTAMP '2018-10-05 01:30:00','Another message in guestbook 5.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 6',TIMESTAMP '2018-10-06 01:30:00','Another message in guestbook 6.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 7',TIMESTAMP '2018-10-07 01:30:00','Another message in guestbook 7.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 8',TIMESTAMP '2018-10-08 01:30:00','Another message in guestbook 8.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 9',TIMESTAMP '2018-10-09 01:30:00','Another message in guestbook 9.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 10',TIMESTAMP '2018-10-10 01:30:00','Another message in guestbook 10.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 11',TIMESTAMP '2018-10-11 01:30:00','Another message in guestbook 11.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 12',TIMESTAMP '2018-10-12 01:30:00','Another message in guestbook 12.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 13',TIMESTAMP '2018-10-13 01:30:00','Another message in guestbook 13.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 14',TIMESTAMP '2018-10-14 01:30:00','Another message in guestbook 14.');
INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'User 15',TIMESTAMP '2018-10-15 01:30:00','Another message in guestbook 15.');

INSERT INTO GUESTBOOK_MESSAGE (ID,AUTHOR,CREATION_DATE,TEXT) VALUES(NEXTVAL('HIBERNATE_SEQUENCE'),'Alfréd',CURRENT_TIMESTAMP(),'Something really important just now!'); 